//! Exercise the shipping ACL through Tauri's IPC dispatcher, without starting
//! the core, touching credentials, or performing a permitted command's effects.
//! A mock context would have an empty authority and silently allow app commands;
//! only the runtime and the final command handler are mocked here.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Value, json};
use tauri::{
    App, WebviewWindow, WebviewWindowBuilder,
    ipc::CallbackFn,
    test::{INVOKE_KEY, MockRuntime, get_ipc_response, mock_builder},
    utils::acl::{APP_ACL_KEY, manifest::Manifest},
    webview::InvokeRequest,
};

const VIEWER_COMMANDS: [&str; 4] = [
    "desk_viewer_token",
    "transfer_begin",
    "transfer_write",
    "transfer_end",
];
const LIB_SOURCE: &str = include_str!("../src/lib.rs");
const BUILD_SOURCE: &str = include_str!("../build.rs");

fn command_set(commands: impl IntoIterator<Item = impl Into<String>>) -> BTreeSet<String> {
    let commands: Vec<String> = commands.into_iter().map(Into::into).collect();
    let set: BTreeSet<String> = commands.iter().cloned().collect();
    assert_eq!(
        set.len(),
        commands.len(),
        "duplicate commands or permissions"
    );
    set
}

// These deliberately small source readers fail on an unfamiliar list shape,
// rather than silently missing commands. Both cfg branches must be checked on
// every host, not just the one cargo happens to compile today.
fn list_after<'a>(source: &'a str, marker: &str) -> &'a str {
    let (_, rest) = source.split_once(marker).expect("command list marker");
    rest.split_once(']').expect("end of command list").0
}

fn handler_commands(macos: bool) -> BTreeSet<String> {
    let cfg = if macos {
        "#[cfg(target_os = \"macos\")]\n    let builder = builder.invoke_handler("
    } else {
        "#[cfg(not(target_os = \"macos\"))]\n    let builder = builder.invoke_handler("
    };
    let (_, branch) = LIB_SOURCE.split_once(cfg).expect("platform invoke handler");
    command_set(
        list_after(branch, "tauri::generate_handler![")
            .split(',')
            .map(str::trim)
            .filter(|command| !command.is_empty())
            .map(|command| {
                assert!(
                    command
                        .chars()
                        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':')
                );
                command.rsplit("::").next().unwrap()
            }),
    )
}

fn manifest_commands() -> BTreeSet<String> {
    assert_eq!(BUILD_SOURCE.matches(".commands(&[").count(), 1);
    command_set(
        list_after(BUILD_SOURCE, ".commands(&[")
            .split(',')
            .map(str::trim)
            .filter(|command| !command.is_empty())
            .map(|command| serde_json::from_str::<String>(command).expect("quoted command name")),
    )
}

fn generated_manifests() -> BTreeMap<String, Manifest> {
    // The same build-script output that generate_context! resolves, including
    // permissions/main.toml and the AppManifest's autogenerated allow/deny files.
    serde_json::from_str(include_str!(concat!(
        env!("OUT_DIR"),
        "/acl-manifests.json"
    )))
    .expect("generated ACL manifests")
}

#[test]
fn handlers_app_manifest_and_main_permission_set_stay_in_sync() {
    assert_eq!(LIB_SOURCE.matches("tauri::generate_handler![").count(), 2);
    let macos = handler_commands(true);
    let other = handler_commands(false);
    assert!(macos.contains("notify"));
    assert!(!other.contains("notify"));
    let mut common = macos.clone();
    common.remove("notify");
    assert_eq!(
        common, other,
        "notify is the only platform-specific app command"
    );

    let commands = manifest_commands();
    assert_eq!(
        commands, macos,
        "AppManifest must contain the full macOS superset"
    );
    let manifests = generated_manifests();
    let app = manifests.get(APP_ACL_KEY).expect("app ACL must exist");
    let main = app
        .permission_sets
        .get("main-commands")
        .expect("main permission set");
    let expected_permissions = command_set(
        commands
            .iter()
            .map(|command| format!("allow-{}", command.replace('_', "-"))),
    );
    assert_eq!(command_set(main.permissions.clone()), expected_permissions);

    let allowed = command_set(
        app.permissions
            .values()
            .flat_map(|permission| permission.commands.allow.iter().cloned()),
    );
    assert_eq!(
        allowed, commands,
        "generated app permissions must cover exactly the manifest"
    );
    for command in &commands {
        let permission = &app.permissions[&format!("allow-{}", command.replace('_', "-"))];
        assert_eq!(permission.commands.allow, vec![command.clone()]);
        assert!(permission.commands.deny.is_empty());
    }
}

#[test]
fn viewer_capability_is_an_exact_local_only_allowlist() {
    let viewer: Value = serde_json::from_str(include_str!("../capabilities/viewer.json")).unwrap();
    assert_eq!(viewer["identifier"], "viewer");
    assert_eq!(viewer["windows"], json!(["computer-*"]));
    assert!(
        viewer.get("webviews").is_none(),
        "webview matches can widen window scope"
    );
    assert!(
        viewer.get("remote").is_none(),
        "no remote origins are trusted"
    );
    assert!(
        viewer
            .get("local")
            .is_none_or(|local| local == &json!(true))
    );
    let permissions = viewer["permissions"].as_array().unwrap();
    assert_eq!(
        command_set(
            permissions
                .iter()
                .map(|permission| permission.as_str().expect("plain permission identifier"))
        ),
        command_set(VIEWER_COMMANDS.map(|command| format!("allow-{}", command.replace('_', "-"))))
    );

    let main: Value = serde_json::from_str(include_str!("../capabilities/default.json")).unwrap();
    assert_eq!(main["windows"], json!(["main"]));
    assert!(
        main["permissions"]
            .as_array()
            .unwrap()
            .contains(&json!("main-commands"))
    );

    // Capabilities are additive: a second capability must not grant a remote
    // origin access behind the viewer file's otherwise correct allowlist.
    let capabilities: BTreeMap<String, Value> =
        serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/capabilities.json"))).unwrap();
    for (name, capability) in capabilities {
        assert!(
            capability["remote"].is_null(),
            "{name} trusts a remote origin"
        );
    }
}

fn acl_app() -> App<MockRuntime> {
    mock_builder()
        .invoke_handler(|invoke| {
            // Success means the actual dispatcher admitted the command, not
            // that some handler rejected missing arguments or missing state.
            assert!(invoke.acl.is_some(), "app command bypassed the ACL");
            let command = invoke.message.command().to_owned();
            invoke.resolver.resolve(command);
            true
        })
        // Keep the shipping config and generated authority; only frontend
        // assets and macOS's executable plist embedding are unnecessary here.
        .build(tauri::generate_context!(
            assets = tauri::test::noop_assets(),
            test = true
        ))
        .expect("build mock runtime with shipping generated ACL")
}

fn window(app: &App<MockRuntime>, label: &str) -> WebviewWindow<MockRuntime> {
    WebviewWindowBuilder::new(app, label, Default::default())
        .build()
        .expect("mock webview window")
}

fn local_origin() -> &'static str {
    if cfg!(any(windows, target_os = "android")) {
        "http://tauri.localhost"
    } else {
        "tauri://localhost"
    }
}

fn invoke(
    window: &WebviewWindow<MockRuntime>,
    command: &str,
    origin: &str,
) -> Result<String, Value> {
    get_ipc_response(
        window,
        InvokeRequest {
            cmd: command.into(),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: origin.parse().unwrap(),
            body: Default::default(),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.into(),
        },
    )
    .map(|body| body.deserialize::<String>().expect("stub command response"))
}

fn assert_denied(window: &WebviewWindow<MockRuntime>, command: &str, origin: &str) {
    let error = invoke(window, command, origin).expect_err("IPC must be denied before the handler");
    let message = error.as_str().expect("ACL rejection message");
    assert!(
        message.contains("not allowed") || message.contains("denied"),
        "{command} from {origin} failed for a reason other than ACL denial: {message}"
    );
}

#[test]
fn main_can_invoke_every_manifest_command_at_the_permission_layer() {
    let app = acl_app();
    let main = window(&app, "main");
    // notify is intentionally present in the cross-platform ACL superset even
    // where production uses the notification plugin instead of an app handler.
    for command in manifest_commands() {
        assert_eq!(invoke(&main, &command, local_origin()), Ok(command));
    }
    assert_denied(&main, "unregistered_command", local_origin());
}

#[test]
fn computer_viewers_can_invoke_only_the_four_viewer_commands() {
    let app = acl_app();
    for label in ["computer-alice", "computer-remote-desk-bob"] {
        let viewer = window(&app, label);
        for command in manifest_commands() {
            if VIEWER_COMMANDS.contains(&command.as_str()) {
                assert_eq!(invoke(&viewer, &command, local_origin()), Ok(command));
            } else {
                // Includes desk_list (owner credentials), pairing, forgetting,
                // host file access, cookie import and every updater command.
                assert_denied(&viewer, &command, local_origin());
            }
        }
        assert_denied(&viewer, "unregistered_command", local_origin());
        // Also catch additive capabilities granting plugin authority. A
        // missing plugin/handler is not enough: assert_denied requires an ACL
        // rejection, before dispatch to any plugin can take place.
        for (plugin, manifest) in generated_manifests() {
            if plugin == APP_ACL_KEY {
                continue;
            }
            let plugin = plugin.strip_prefix("core:").unwrap_or(&plugin);
            let commands: BTreeSet<_> = manifest
                .permissions
                .values()
                .flat_map(|permission| &permission.commands.allow)
                .collect();
            for command in commands {
                assert_denied(
                    &viewer,
                    &format!("plugin:{plugin}|{command}"),
                    local_origin(),
                );
            }
        }
    }
}

#[test]
fn unrelated_window_labels_have_no_app_command_permissions() {
    let app = acl_app();
    for label in ["computer", "computerish-alice", "main-copy", "other"] {
        let unrelated = window(&app, label);
        for command in manifest_commands() {
            assert_denied(&unrelated, &command, local_origin());
        }
    }
}

#[test]
fn remote_origins_cannot_use_main_or_viewer_permissions() {
    let app = acl_app();
    for label in ["main", "computer-alice"] {
        let webview = window(&app, label);
        for origin in ["https://attacker.example/", "http://127.0.0.1:49152/"] {
            for command in manifest_commands() {
                assert_denied(&webview, &command, origin);
            }
        }
    }
}
