//! These tests enter the real desk through HTTPS/WSS; the trust root is the
//! certificate generated by this disposable listener, never an insecure client.
use super::*;
use crate::{
    contract::{SessionInfo, StreamDelta},
    credentials::tests::MemoryStore,
    desk::Desk,
    wire::Door,
};
use futures_util::{SinkExt, StreamExt};
use std::time::Duration;
use tokio::net::TcpStream;
use tokio::sync::broadcast;
use tokio_rustls::{TlsConnector, client::TlsStream, rustls};
use tokio_tungstenite::{
    WebSocketStream,
    tungstenite::{Message, client::IntoClientRequest},
};

type Socket = WebSocketStream<TlsStream<TcpStream>>;
struct Harness {
    root: tempfile::TempDir,
    remote: Arc<Remote>,
    desk: Arc<Desk>,
    store: Arc<MemoryStore>,
    http: reqwest::Client,
    tls: TlsConnector,
}
impl Harness {
    async fn new() -> Self {
        Self::around(|desk| desk).await
    }
    /// A desk that reports a computer it does not have, for the door to open.
    async fn with_computer() -> (Self, Arc<Computered>) {
        let mut handle = None;
        let harness = Self::around(|desk| {
            let room = Arc::new(Computered {
                desk,
                viewer: std::sync::Mutex::new(None),
            });
            handle = Some(room.clone());
            room
        })
        .await;
        (harness, handle.unwrap())
    }
    async fn around(room_of: impl FnOnce(Arc<Desk>) -> Arc<dyn RoomHandle>) -> Self {
        let root = tempfile::tempdir().unwrap();
        // Harnesses run side by side; none may claim the install default port
        // another one's re-enable expects to get back.
        let port = std::net::TcpListener::bind("[::]:0")
            .or_else(|_| std::net::TcpListener::bind("0.0.0.0:0"))
            .unwrap()
            .local_addr()
            .unwrap()
            .port();
        fs::write(
            root.path().join("remote.json"),
            json!({"desktopId": Uuid::new_v4(), "host": network::ALL, "port": port, "enabled": false, "grants": []}).to_string(),
        )
        .unwrap();
        let store = Arc::new(MemoryStore::default());
        let desk = Arc::new(Desk::open_with_store(root.path(), store.clone()).unwrap());
        let remote = Remote::open_with_store(
            root.path(),
            desk.log.clone(),
            room_of(desk.clone()),
            store.clone(),
        )
        .unwrap();
        assert!(!remote.status().enabled);
        remote.configure(true, network::ALL).await.unwrap();
        let identity: Identity =
            serde_json::from_slice(&remote.identity.read().unwrap().unwrap()).unwrap();
        let mut roots = rustls::RootCertStore::empty();
        roots
            .add(rustls::pki_types::CertificateDer::from(
                identity.certificate.clone(),
            ))
            .unwrap();
        let config = rustls::ClientConfig::builder_with_provider(Arc::new(
            rustls::crypto::aws_lc_rs::default_provider(),
        ))
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(roots)
        .with_no_client_auth();
        let http = reqwest::Client::builder()
            .no_proxy()
            .add_root_certificate(reqwest::Certificate::from_der(&identity.certificate).unwrap())
            .build()
            .unwrap();
        Self {
            root,
            remote,
            desk,
            store,
            http,
            tls: TlsConnector::from(Arc::new(config)),
        }
    }
    fn endpoint(&self) -> String {
        self.remote.status().endpoint.unwrap()
    }
    async fn claim(&self, value: &Value) -> reqwest::Response {
        self.http
            .post(format!("{}/pair", self.endpoint()))
            .json(value)
            .send()
            .await
            .unwrap()
    }
    async fn post(&self, path: &str, value: &Value) -> reqwest::Response {
        self.http
            .post(format!("{}{path}", self.endpoint()))
            .json(value)
            .send()
            .await
            .unwrap()
    }
    async fn pair(&self) -> Value {
        let invite = self.remote.pairing().unwrap().invitation;
        self.claim_invitation(invite).await
    }
    /// Scans the invitation already on screen rather than minting one.
    async fn pair_current(&self) -> Value {
        let invite = self
            .remote
            .state
            .lock()
            .unwrap()
            .invitation
            .as_ref()
            .unwrap()
            .value
            .clone();
        self.claim_invitation(invite).await
    }
    async fn claim_invitation(&self, invite: PairingInvitation) -> Value {
        self.claim(&json!({"invitationId":invite.invitation_id,"secret":invite.secret,"claimId":Uuid::new_v4(),"name":"Test phone"}))
            .await.error_for_status().unwrap().json().await.unwrap()
    }
    async fn socket(&self, token: &str) -> Result<Socket, tokio_tungstenite::tungstenite::Error> {
        self.socket_at("/ws", token).await
    }
    async fn socket_at(
        &self,
        path: &str,
        token: &str,
    ) -> Result<Socket, tokio_tungstenite::tungstenite::Error> {
        let endpoint = self.endpoint();
        let stream = TcpStream::connect(endpoint.trim_start_matches("https://"))
            .await
            .unwrap();
        let tls = self
            .tls
            .connect(
                rustls::pki_types::ServerName::try_from(
                    url::Url::parse(&endpoint)
                        .unwrap()
                        .host_str()
                        .unwrap()
                        .trim_matches(['[', ']'])
                        .to_owned(),
                )
                .unwrap(),
                stream,
            )
            .await
            .unwrap();
        let mut request = format!("{}{path}", endpoint.replace("https:", "wss:"))
            .into_client_request()
            .unwrap();
        request
            .headers_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        tokio_tungstenite::client_async(request, tls)
            .await
            .map(|v| v.0)
    }
}
async fn read(socket: &mut Socket) -> Value {
    let frame = tokio::time::timeout(Duration::from_secs(3), socket.next())
        .await
        .unwrap()
        .unwrap()
        .unwrap();
    serde_json::from_str(frame.to_text().unwrap()).unwrap()
}
async fn send(socket: &mut Socket, frame: Value) {
    socket.send(Message::text(frame.to_string())).await.unwrap();
}

#[tokio::test]
async fn pairing_is_single_use_persistent_and_revocation_closes_the_live_wire() {
    let h = Harness::new().await;
    let invitation = h.remote.pairing().unwrap().invitation;
    let mut claim = json!({"invitationId":invitation.invitation_id,"secret":"wrong","claimId":Uuid::new_v4(),"name":"My phone"});
    assert_eq!(h.claim(&claim).await.status(), 403);
    claim["secret"] = json!(invitation.secret);
    let grant: Value = h.claim(&claim).await.json().await.unwrap();
    assert_eq!(grant, h.claim(&claim).await.json::<Value>().await.unwrap());
    claim["claimId"] = json!(Uuid::new_v4());
    assert_eq!(h.claim(&claim).await.status(), 403);
    assert!(h.socket("desk-token").await.is_err());
    let token = grant["token"].as_str().unwrap();
    assert!(
        !fs::read_to_string(h.root.path().join("remote.json"))
            .unwrap()
            .contains(token)
    );
    let mut socket = h.socket(token).await.unwrap();
    assert_eq!(read(&mut socket).await["mode"], "team");
    h.remote
        .revoke(grant["deviceId"].as_str().unwrap())
        .unwrap();
    let closed = tokio::time::timeout(Duration::from_secs(3), socket.next())
        .await
        .unwrap();
    assert!(!matches!(closed, Some(Ok(Message::Text(_)))));
    assert!(h.socket(token).await.is_err());
    assert_eq!(h.claim(&claim).await.status(), 403);
    let next = h.pair().await;
    let endpoint = h.endpoint();
    let fingerprint = h.remote.pairing().unwrap().invitation.certificate_sha256;
    h.remote.configure(false, network::ALL).await.unwrap();
    assert!(
        TcpStream::connect(endpoint.trim_start_matches("https://"))
            .await
            .is_err()
    );
    let restored = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        h.store.clone(),
    )
    .unwrap();
    restored.configure(true, network::ALL).await.unwrap();
    assert_eq!(restored.status().endpoint.unwrap(), endpoint);
    assert_eq!(
        restored.pairing().unwrap().invitation.certificate_sha256,
        fingerprint
    );
    assert!(
        restored
            .authenticate(next["token"].as_str().unwrap())
            .is_some()
    );
    restored.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn a_phone_sees_the_real_roster_and_tape_but_cannot_administer_the_desk() {
    let h = Harness::new().await;
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}/v1", listener.local_addr().unwrap());
    let calls = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let counted = calls.clone();
    let requests = Arc::new(Mutex::new(Vec::<Value>::new()));
    let captured = requests.clone();
    let app = axum::Router::new().route("/v1/chat/completions", axum::routing::post(move |body: String| {
        captured.lock().unwrap().push(serde_json::from_str(&body).unwrap());
        counted.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        async {
            let chunk = json!({"id":"chat_1","object":"chat.completion.chunk","created":1,"model":"test","choices":[{"index":0,"delta":{"role":"assistant","content":"A real core turn"},"finish_reason":null}]});
            let end = json!({"id":"chat_1","object":"chat.completion.chunk","created":1,"model":"test","choices":[{"index":0,"delta":{},"finish_reason":"stop"}]});
            ([("Content-Type", "text/event-stream")], format!("data: {chunk}\n\ndata: {end}\n\ndata: [DONE]\n\n"))
        }
    }));
    let model = tokio::spawn(async move {
        axum::serve(listener, app).await.unwrap();
    });
    h.desk.credential_custom_save(None, serde_json::from_value(json!({"name":"Fixture", "baseUrl":base, "api":"chat_completions", "secret":"", "models":["test"]})).unwrap()).unwrap();
    let door = Door::bind(h.desk.log.clone(), "test-desk".into(), h.desk.clone()).unwrap();
    let port = door.port();
    let task = tokio::spawn(door.run());
    let (mut desk, _) =
        tokio_tungstenite::connect_async(format!("ws://127.0.0.1:{port}/ws?token=test-desk"))
            .await
            .unwrap();
    desk.send(Message::text(json!({"id":1,"cmd":"persona.create","params":{"draft":{"name":"Ada","goal":"Help with the project","cwd":h.root.path().to_str().unwrap()}}}).to_string())).await.unwrap();
    let created: Value =
        serde_json::from_str(desk.next().await.unwrap().unwrap().to_text().unwrap()).unwrap();
    let persona = created["result"]["id"].as_str().unwrap();
    // The window may say the person is at it; a phone may not, or it could
    // keep its own notifications away.
    desk.send(Message::text(
        json!({"id":2,"cmd":"desk.looking","params":{"looking":true}}).to_string(),
    ))
    .await
    .unwrap();
    let looking: Value =
        serde_json::from_str(desk.next().await.unwrap().unwrap().to_text().unwrap()).unwrap();
    assert_eq!(looking["ok"], true, "{looking}");
    let grant = h.pair().await;
    let mut phone = h.socket(grant["token"].as_str().unwrap()).await.unwrap();
    read(&mut phone).await;
    for frame in [
        json!({"id":1,"cmd":"credential.list"}),
        json!({"id":1,"cmd":"settings.update","params":{"patch":{}}}),
        json!({"id":1,"sub":"room"}),
        json!({"id":1,"cmd":"session.prompt","params":{"personaId":persona,"text":"bad","attachments":[]}}),
        json!({"id":1,"cmd":"desk.looking","params":{"looking":true}}),
    ] {
        send(&mut phone, frame).await;
        assert_eq!(read(&mut phone).await["ok"], false);
    }
    send(&mut phone, json!({"id":2,"sub":{"view":"roster"}})).await;
    assert_eq!(read(&mut phone).await["ok"], true);
    assert_eq!(
        read(&mut phone).await["snapshot"][0]["persona"]["name"],
        "Ada"
    );
    send(&mut phone, json!({"id":3,"sub":{"tape":persona}})).await;
    assert_eq!(read(&mut phone).await["ok"], true);
    assert_eq!(read(&mut phone).await["snapshot"], json!([]));
    // The core remains the writer; this tests that its append reaches the TLS subscription.
    h.desk
        .log
        .append(
            &crate::log::StreamId::Tape(persona.into()),
            &json!({"id":"one","kind":"agent","ts":1,"text":"From the real tape"}),
        )
        .unwrap();
    loop {
        let frame = read(&mut phone).await;
        if frame["sub"] == 3 {
            assert_eq!(frame["event"]["text"], "From the real tape");
            break;
        }
    }
    // The phone is the first client to start this teammate. Retransmitting
    // its operation after acceptance must not start a second model turn.
    let attachment = Uuid::new_v4();
    send(&mut phone, json!({"id":30,"cmd":"mobile.attachment","params":{"upload":{"id":attachment,"name":"brief.txt","mimeType":"text/plain","size":5,"offset":0,"data":"aGVsbG8="}}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 30 {
            assert_eq!(frame["result"]["complete"], true, "{frame}");
            break;
        }
    }
    let operation = Uuid::new_v4();
    send(&mut phone, json!({"id":4,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"","attachmentIds":[attachment],"replyTo":"answered-1"}})).await;
    let mut accepted = false;
    let mut answered = false;
    while !accepted || !answered {
        let frame = read(&mut phone).await;
        if frame["id"] == 4 {
            assert_eq!(frame["result"]["state"], "accepted", "{frame}");
            accepted = true;
        }
        if frame["sub"] == 3
            && frame["event"]["kind"] == "agent"
            && frame["event"]["text"] == "A real core turn"
        {
            answered = true;
        }
    }
    send(&mut phone, json!({"id":5,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"","attachmentIds":[attachment],"replyTo":"answered-1"}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 5 {
            assert_eq!(frame["result"]["state"], "accepted");
            break;
        }
    }
    assert_eq!(calls.load(std::sync::atomic::Ordering::SeqCst), 1);
    let tape = h.desk.log.load(&crate::log::StreamId::Tape(persona.into()));
    let users: Vec<_> = tape
        .iter()
        .filter(|event| event["kind"] == "user")
        .collect();
    assert_eq!(users.len(), 1);
    assert_eq!(users[0]["text"], "");
    assert_eq!(users[0]["attachments"][0]["name"], "brief.txt");
    assert_eq!(users[0]["replyTo"], "answered-1");
    let path = users[0]["attachments"][0]["path"].as_str().unwrap();
    assert_eq!(fs::read(path).unwrap(), b"hello");
    // The request is JSON, where a Windows path's backslashes are escaped.
    let path_in_json = serde_json::to_string(path).unwrap();
    assert!(
        requests.lock().unwrap()[0]
            .to_string()
            .contains(path_in_json.trim_matches('"'))
    );
    send(&mut phone, json!({"id":6,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"changed","attachmentIds":[]}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 6 {
            assert_eq!(frame["ok"], false);
            break;
        }
    }
    h.remote.configure(false, network::ALL).await.unwrap();
    model.abort();
    task.abort();
}

/// A paired phone reads one teammate's schedules through the real door: an
/// empty list said out loud, each change as the whole list, a refusal for
/// anything that would change a job or reach the room, and on reconnecting
/// the list as it now is, with what changed while it was away. A revoked
/// phone reads nothing.
#[tokio::test]
async fn a_phone_reads_a_teammates_schedules_and_catches_up_on_what_changed_while_away() {
    let h = Harness::new().await;
    let door = Door::bind(h.desk.log.clone(), "test-desk".into(), h.desk.clone()).unwrap();
    let port = door.port();
    let task = tokio::spawn(door.run());
    let (mut desk, _) =
        tokio_tungstenite::connect_async(format!("ws://127.0.0.1:{port}/ws?token=test-desk"))
            .await
            .unwrap();
    let mut asked = 0;
    let mut at_desk = async |cmd: &str, params: Value| -> Value {
        asked += 1;
        desk.send(Message::text(
            json!({"id": asked, "cmd": cmd, "params": params}).to_string(),
        ))
        .await
        .unwrap();
        loop {
            let frame: Value =
                serde_json::from_str(desk.next().await.unwrap().unwrap().to_text().unwrap())
                    .unwrap();
            if frame["id"] == asked {
                assert_eq!(frame["ok"], true, "{cmd}: {frame}");
                return frame["result"].clone();
            }
        }
    };
    let cwd = h.root.path().to_str().unwrap();
    let ada = at_desk(
        "persona.create",
        json!({"draft": {"name": "Ada", "goal": "Keep the harbour running", "cwd": cwd}}),
    )
    .await["id"]
        .as_str()
        .unwrap()
        .to_string();
    let bob = at_desk(
        "persona.create",
        json!({"draft": {"name": "Bob", "goal": "Count the boats", "cwd": cwd}}),
    )
    .await["id"]
        .as_str()
        .unwrap()
        .to_string();

    let grant = h.pair().await;
    let token = grant["token"].as_str().unwrap();
    let mut phone = h.socket(token).await.unwrap();
    // The hello is how a phone knows it may ask; a desk from before this
    // list names nothing, and the phone then shows no schedules section.
    assert_eq!(
        read(&mut phone).await["capabilities"],
        json!(["schedules", "threads"])
    );

    send(&mut phone, json!({"id": 1, "sub": {"schedules": ada}})).await;
    assert_eq!(read(&mut phone).await, json!({"id": 1, "ok": true}));
    assert_eq!(read(&mut phone).await, json!({"sub": 1, "snapshot": []}));

    let sweep = at_desk(
        "schedule.create",
        json!({"personaId": ada, "kind": "loop", "every": 3_600_000, "prompt": "Sweep the inbox"}),
    )
    .await;
    let listed = read(&mut phone).await;
    assert_eq!(listed["sub"], 1, "{listed}");
    let entry = &listed["snapshot"][0];
    assert_eq!(entry["id"], sweep["id"]);
    assert_eq!(entry["personaId"], ada.as_str());
    assert_eq!(entry["kind"], "loop");
    assert_eq!(entry["every"], 3_600_000);
    assert_eq!(entry["prompt"], "Sweep the inbox");
    assert_eq!(entry["nextAt"], sweep["nextAt"]);
    // Who made a job is the desk's business, not a display field.
    assert!(entry.get("operatorCreated").is_none(), "{entry}");
    assert_eq!(listed["snapshot"].as_array().unwrap().len(), 1);

    let refusals = [
        json!({"id": 2, "cmd": "schedule.create", "params": {"personaId": ada, "kind": "loop", "every": 60_000, "prompt": "Not from here"}}),
        json!({"id": 3, "cmd": "schedule.cancel", "params": {"id": sweep["id"]}}),
        json!({"id": 4, "cmd": "schedule.set_quiet", "params": {"id": sweep["id"], "quiet": true}}),
        json!({"id": 5, "cmd": "schedule.list"}),
        json!({"id": 6, "sub": "room"}),
    ];
    for frame in refusals {
        let id = frame["id"].clone();
        send(&mut phone, frame).await;
        let refused = read(&mut phone).await;
        assert_eq!(refused["id"], id, "{refused}");
        assert_eq!(refused["ok"], false, "{refused}");
        assert_eq!(refused["code"], "forbidden", "{refused}");
    }
    send(&mut phone, json!({"id": 7, "sub": {"schedules": "nobody"}})).await;
    let unknown = read(&mut phone).await;
    assert_eq!(unknown["ok"], false, "{unknown}");
    assert_eq!(unknown["code"], "unknown_teammate", "{unknown}");
    // Nothing the phone asked for moved a job.
    assert_eq!(h.desk.schedule_list().len(), 1);

    // Away: the loop is cancelled, a one-shot is made, and Bob gets a job of
    // his own. Back, the list is what is true now.
    phone.close(None).await.unwrap();
    drop(phone);
    at_desk("schedule.cancel", json!({"id": sweep["id"]})).await;
    let when = crate::session::now_ms() + 3_600_000;
    let once = at_desk(
        "schedule.create",
        json!({"personaId": ada, "kind": "schedule", "when": when, "prompt": "Check the crane"}),
    )
    .await;
    at_desk(
        "schedule.create",
        json!({"personaId": bob, "kind": "loop", "every": 3_600_000, "prompt": "Count the boats"}),
    )
    .await;
    let mut phone = h.socket(token).await.unwrap();
    read(&mut phone).await;
    send(&mut phone, json!({"id": 1, "sub": {"schedules": ada}})).await;
    assert_eq!(read(&mut phone).await, json!({"id": 1, "ok": true}));
    let now = read(&mut phone).await;
    let jobs = now["snapshot"].as_array().unwrap();
    assert_eq!(jobs.len(), 1, "{now}");
    assert_eq!(jobs[0]["id"], once["id"]);
    assert_eq!(jobs[0]["kind"], "schedule");
    assert_eq!(jobs[0]["when"], when);
    assert_eq!(jobs[0]["nextAt"], when);

    // Revoked, the phone's socket closes and cannot be opened again.
    h.remote
        .revoke(grant["deviceId"].as_str().unwrap())
        .unwrap();
    let closed = tokio::time::timeout(Duration::from_secs(3), phone.next())
        .await
        .unwrap();
    assert!(!matches!(closed, Some(Ok(Message::Text(_)))), "{closed:?}");
    assert!(h.socket(token).await.is_err());

    h.remote.configure(false, network::ALL).await.unwrap();
    task.abort();
}

#[tokio::test]
async fn an_uncertain_prompt_is_never_replayed_and_operation_ids_cannot_change_meaning() {
    let h = Harness::new().await;
    let grant = h.pair().await;
    let phone = h
        .remote
        .authenticate(grant["token"].as_str().unwrap())
        .unwrap();
    let operation = Uuid::new_v4().to_string();
    let dir = h.root.path().join("remote-receipts").join(&phone.id);
    fs::create_dir_all(&dir).unwrap();
    let path = dir.join(format!("{operation}.json"));
    let receipt = Receipt {
        digest: hash(&json!(["persona", "hello"]).to_string()),
        result: None,
    };
    atomic_write(&path, &serde_json::to_vec(&receipt).unwrap()).unwrap();
    assert_eq!(
        phone
            .prompt(&operation, "persona", "hello", &[], None)
            .await
            .unwrap()["state"],
        "unknown"
    );
    assert!(
        phone
            .prompt(&operation, "persona", "changed", &[], None)
            .await
            .is_err()
    );
    let receipt = Receipt {
        result: Some(Ok(())),
        ..receipt
    };
    atomic_write(&path, &serde_json::to_vec(&receipt).unwrap()).unwrap();
    assert_eq!(
        phone
            .prompt(&operation, "persona", "hello", &[], None)
            .await
            .unwrap()["state"],
        "accepted"
    );
    h.remote.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn all_interfaces_are_the_default_and_every_advertised_ip_has_valid_tls() {
    let h = Harness::new().await;
    let status = h.remote.status();
    assert_eq!(status.host, network::ALL);
    assert!(status.enabled);
    assert_eq!(status.endpoints.len(), status.addresses.len());
    for endpoint in &status.endpoints {
        let response = h
            .http
            .get(format!("{endpoint}/missing"))
            .timeout(Duration::from_secs(3))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 404);
    }
    let invitation = h.remote.pairing().unwrap().invitation;
    assert_eq!(Some(invitation.endpoint), status.endpoint);
    for host in ["127.0.0.1", "127.2.3.4", "::1", "0.0.0.0", "::"] {
        assert!(h.remote.configure(true, host).await.is_err());
        assert_eq!(h.remote.status().endpoints, status.endpoints);
    }
    let grant = h.pair().await;
    let token = grant["token"].as_str().unwrap();
    let specific = status.addresses[0].clone();
    let narrowed = h.remote.configure(true, &specific).await.unwrap();
    assert_eq!(narrowed.host, specific);
    assert_eq!(narrowed.endpoints, vec![status.endpoint.clone().unwrap()]);
    assert!(h.remote.authenticate(token).is_some());
    assert_eq!(
        h.remote.pairing().unwrap().invitation.certificate_sha256,
        invitation.certificate_sha256
    );
    for other in status.endpoints.iter().skip(1) {
        let result = h
            .http
            .get(format!("{other}/missing"))
            .timeout(Duration::from_secs(1))
            .send()
            .await;
        assert!(result.is_err(), "restricted listener accepted {other}");
    }
    let off = h.remote.configure(false, network::ALL).await.unwrap();
    assert!(!off.enabled);
    assert_eq!(off.host, network::ALL);
    assert!(off.endpoints.is_empty());
    assert!(h.remote.authenticate(token).is_none());
    assert_eq!(
        h.remote
            .configure(true, network::ALL)
            .await
            .unwrap()
            .endpoints,
        status.endpoints
    );
    assert!(h.remote.authenticate(token).is_some());
    h.remote.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn a_saved_loopback_selection_migrates_to_all_host_ips() {
    let h = Harness::new().await;
    h.remote.configure(false, network::ALL).await.unwrap();
    let path = h.root.path().join("remote.json");
    let mut saved: Saved = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    saved.host = "127.0.0.1".into();
    atomic_write(&path, &serde_json::to_vec(&saved).unwrap()).unwrap();
    let restored = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        h.store.clone(),
    )
    .unwrap();
    assert_eq!(restored.status().host, network::ALL);
    assert!(!restored.status().enabled);
    assert!(
        restored
            .status()
            .addresses
            .iter()
            .all(|host| network::reachable(host.parse().unwrap()))
    );
    restored.configure(true, network::ALL).await.unwrap();
    let saved: Saved = serde_json::from_slice(&fs::read(path).unwrap()).unwrap();
    assert_eq!(saved.host, network::ALL);
    restored.configure(false, network::ALL).await.unwrap();
}

/// An OS store that is locked: every call is refused and nothing is lost.
struct LockedStore;
impl SecretStore for LockedStore {
    fn get(&self, _: &str) -> io::Result<Option<Vec<u8>>> {
        Err(locked())
    }
    fn set(&self, _: &str, _: &[u8]) -> io::Result<()> {
        Err(locked())
    }
    fn delete(&self, _: &str) -> io::Result<()> {
        Err(locked())
    }
}
fn locked() -> io::Error {
    io::Error::new(io::ErrorKind::PermissionDenied, "store locked")
}

/// A room moved over from Toad holds that edition's reference to the
/// listener's certificate, which this build cannot read. Remote comes up on
/// a fresh certificate rather than refusing to turn on, and the phones that
/// pinned the old one are forgotten, as when an address changes. A store
/// that is merely locked is the other case: what it holds is reported,
/// never replaced.
#[tokio::test]
async fn an_unreadable_identity_is_replaced_but_a_locked_store_is_reported() {
    let h = Harness::new().await;
    h.remote.configure(false, network::ALL).await.unwrap();
    let identity = h.root.path().join("remote-identity.json");
    let ours = fs::read(&identity).unwrap();
    let path = h.root.path().join("remote.json");
    let mut saved: Saved = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    saved.grants.push(Grant {
        device: RemoteDevice {
            id: "phone".into(),
            name: "Phone".into(),
            paired_at: now(),
        },
        token_hash: hash("token"),
        push: None,
    });
    atomic_write(&path, &serde_json::to_vec(&saved).unwrap()).unwrap();

    let locked = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        Arc::new(LockedStore),
    )
    .unwrap();
    let refused = match locked.configure(true, network::ALL).await {
        Ok(_) => panic!("a locked store must not be replaced"),
        Err(refused) => refused,
    };
    assert!(refused.contains("store locked"), "{refused}");
    assert!(!locked.status().enabled);
    assert_eq!(locked.status().devices.len(), 1);
    assert_eq!(fs::read(&identity).unwrap(), ours);

    let earlier = br#"{"toadCredential":1,"generation":"6f1f9e16-6a0b-4a0e-9f3e-3f4b2f4a7a31","chunks":1,"digest":"7d8e4051a3d929fc56a545c5125a8589a4b4bfedd354466455403038d450144f"}"#;
    fs::write(&identity, earlier).unwrap();
    let restored = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        h.store.clone(),
    )
    .unwrap();
    assert_eq!(restored.status().devices.len(), 1);
    let status = restored.configure(true, network::ALL).await.unwrap();
    assert!(status.enabled);
    assert!(status.error.is_none());
    assert!(status.devices.is_empty());
    let replaced = fs::read(&identity).unwrap();
    assert!(String::from_utf8_lossy(&replaced).contains("hotlineCredential"));
    assert_ne!(replaced, ours);
    restored.configure(false, network::ALL).await.unwrap();
}

/// The phone's half of the manual exchange, as the mobile client does it.
struct TypingPhone {
    claim_id: String,
    secret: Scalar,
    public: String,
}
impl TypingPhone {
    fn new(code: &str) -> Self {
        let claim_id = Uuid::new_v4().to_string();
        let secret = pake::random_scalar();
        let public = pake::public(code, &claim_id, &secret);
        Self {
            claim_id,
            secret,
            public,
        }
    }
    async fn start(&self, h: &Harness) -> reqwest::Response {
        h.post(
            "/pair/manual/start",
            &json!({"claimId": self.claim_id, "name": "Typed phone", "phonePublic": self.public}),
        )
        .await
    }
    /// `cert` is what the phone believes it connected to.
    fn confirm(&self, started: &Value, cert: &str) -> pake::Confirmations {
        let desktop_public = started["desktopPublic"].as_str().unwrap();
        pake::confirmations(
            started["desktopId"].as_str().unwrap(),
            &self.claim_id,
            &self.secret,
            &pake::decode_public(desktop_public).unwrap(),
            &self.public,
            desktop_public,
            cert,
        )
        .unwrap()
    }
    async fn finish(&self, h: &Harness, confirm: &str) -> reqwest::Response {
        h.post(
            "/pair/manual/finish",
            &json!({"claimId": self.claim_id, "confirm": confirm}),
        )
        .await
    }
}

#[tokio::test]
async fn a_typed_code_pairs_through_a_pake_bound_to_the_certificate() {
    let h = Harness::new().await;
    let pairing = h.remote.pairing().unwrap();
    let manual = pairing.manual;
    let cert = pairing.invitation.certificate_sha256.clone();
    assert!(manual.code.len() == 6 && manual.code.bytes().all(|b| b.is_ascii_digit()));
    assert_eq!(
        network::endpoint(&manual.address, manual.port),
        pairing.invitation.endpoint
    );
    assert_eq!(manual.expires_at, pairing.invitation.expires_at);

    // A guess with the wrong code, and the right code seen through a relay's
    // certificate, both fail the same way and each burns its session.
    let guessing = TypingPhone::new("000000");
    let started: Value = guessing.start(&h).await.json().await.unwrap();
    assert_eq!(started["desktopId"], pairing.invitation.desktop_id);
    assert_eq!(started["expiresAt"], manual.expires_at);
    let wrong = guessing.confirm(&started, &cert).phone;
    let refused = guessing.finish(&h, &wrong).await;
    assert_eq!(refused.status(), 403);
    assert_eq!(refused.json::<Value>().await.unwrap()["error"], "bad_code");
    assert_eq!(guessing.finish(&h, &wrong).await.status(), 403);

    let relayed = TypingPhone::new(&manual.code);
    let started: Value = relayed.start(&h).await.json().await.unwrap();
    let seen_through_relay = relayed.confirm(&started, &hex::encode([7u8; 32])).phone;
    let refused = relayed.finish(&h, &seen_through_relay).await;
    assert_eq!(refused.json::<Value>().await.unwrap()["error"], "bad_code");

    // The real phone: the desktop's confirmation proves it saw the same
    // certificate, and the token it hands over opens the wire.
    let phone = TypingPhone::new(&manual.code);
    let started: Value = phone.start(&h).await.json().await.unwrap();
    let tags = phone.confirm(&started, &cert);
    let granted: Value = phone.finish(&h, &tags.phone).await.json().await.unwrap();
    assert_eq!(granted["confirm"], tags.desktop);
    assert_eq!(granted["certificateSha256"], cert);
    assert_eq!(granted["desktopId"], pairing.invitation.desktop_id);
    assert_eq!(
        granted,
        phone
            .finish(&h, &tags.phone)
            .await
            .json::<Value>()
            .await
            .unwrap()
    );
    let mut socket = h.socket(granted["token"].as_str().unwrap()).await.unwrap();
    assert_eq!(read(&mut socket).await["mode"], "team");
    assert_eq!(h.remote.status().devices[0].name, "Typed phone");
    // The pairing session is spent on both paths.
    let invite = pairing.invitation;
    let scan = h.claim(&json!({"invitationId": invite.invitation_id, "secret": invite.secret, "claimId": Uuid::new_v4(), "name": "Scanner"})).await;
    assert_eq!(scan.status(), 403);
    assert_eq!(TypingPhone::new(&manual.code).start(&h).await.status(), 403);

    // Five wrong confirmations kill the code, and a scan closes the typed path.
    let manual = h.remote.pairing().unwrap().manual;
    for attempt in 1..=5 {
        let guess = TypingPhone::new("111111");
        let started: Value = guess.start(&h).await.json().await.unwrap();
        let refused = guess
            .finish(&h, &guess.confirm(&started, &cert).phone)
            .await;
        let expected = if attempt == 5 {
            (429, "too_many_attempts")
        } else {
            (403, "bad_code")
        };
        assert_eq!(refused.status(), expected.0, "attempt {attempt}");
        assert_eq!(refused.json::<Value>().await.unwrap()["error"], expected.1);
    }
    let dead = TypingPhone::new(&manual.code).start(&h).await;
    assert_eq!(dead.status(), 403);
    assert_eq!(
        dead.json::<Value>().await.unwrap()["error"],
        "pairing_closed"
    );
    h.remote.state.lock().unwrap().attempts = 0;
    let manual = h.remote.pairing().unwrap().manual;
    h.pair_current().await;
    assert_eq!(TypingPhone::new(&manual.code).start(&h).await.status(), 403);
    let junk = h
        .post(
            "/pair/manual/start",
            &json!({"claimId": Uuid::new_v4(), "name": "x", "phonePublic": hex::encode([0u8; 32])}),
        )
        .await;
    assert_eq!(junk.status(), 400);
    h.remote.configure(false, network::ALL).await.unwrap();
}

/// A phone says where to notify it; the desk keeps that on the grant, and the
/// room reads it back without holding the remote.
#[tokio::test]
async fn a_phone_registers_where_to_notify_it_and_the_room_can_read_it() {
    let h = Harness::new().await;
    let grant = h.pair().await;
    let phone = h
        .remote
        .authenticate(grant["token"].as_str().unwrap())
        .unwrap();
    assert!(super::push_targets(h.root.path()).tokens.is_empty());
    assert!(
        phone
            .register_push("not a token".into(), "ios".into())
            .is_err()
    );
    assert!(
        phone
            .register_push("ExponentPushToken[abc]".into(), "watch".into())
            .is_err()
    );
    phone
        .register_push("ExponentPushToken[abc]".into(), "ios".into())
        .unwrap();
    let targets = super::push_targets(h.root.path());
    assert_eq!(targets.tokens, ["ExponentPushToken[abc]"]);
    assert_eq!(targets.desktop_id, h.remote.status_desktop_id());
    // A fresh token replaces the old one; revoking the phone drops it.
    phone
        .register_push("ExponentPushToken[def]".into(), "ios".into())
        .unwrap();
    assert_eq!(
        super::push_targets(h.root.path()).tokens,
        ["ExponentPushToken[def]"]
    );
    // Turning Remote off keeps the phone paired but stops notifying it.
    h.remote.configure(false, network::ALL).await.unwrap();
    assert!(super::push_targets(h.root.path()).tokens.is_empty());
    h.remote.configure(true, network::ALL).await.unwrap();
    assert_eq!(
        super::push_targets(h.root.path()).tokens,
        ["ExponentPushToken[def]"]
    );
    h.remote.revoke(&phone.id).unwrap();
    assert!(super::push_targets(h.root.path()).tokens.is_empty());
    h.remote.configure(false, network::ALL).await.unwrap();
}

/// The desk with a computer it does not have: every call forwards to the real
/// desk except the one the door asks, which answers with the viewer set here.
struct Computered {
    desk: Arc<Desk>,
    viewer: std::sync::Mutex<Option<String>>,
}

#[async_trait::async_trait]
impl RoomHandle for Computered {
    fn policy_update_lock(&self) -> Arc<tokio::sync::Mutex<()>> {
        self.desk.policy_update_lock()
    }
    async fn start(&self, persona_id: &str) -> Result<SessionInfo, String> {
        self.desk.start(persona_id).await
    }
    fn stop(&self, persona_id: &str) -> Result<(), String> {
        self.desk.stop(persona_id)
    }
    fn invalidate(&self, persona_id: &str) -> Result<(), String> {
        self.desk.invalidate(persona_id)
    }
    fn invalidate_all(&self) -> Result<(), String> {
        self.desk.invalidate_all()
    }
    async fn reattach(&self, persona_id: &str) -> Result<(), String> {
        self.desk.reattach(persona_id).await
    }
    async fn reattach_all(&self) -> Result<(), String> {
        self.desk.reattach_all().await
    }
    async fn prompt(
        &self,
        persona_id: &str,
        text: &str,
        reply_to: Option<String>,
        attachments: Option<Vec<crate::contract::Attachment>>,
    ) -> Result<(), String> {
        self.desk
            .prompt(persona_id, text, reply_to, attachments)
            .await
    }
    fn cancel(&self, persona_id: &str) -> Result<(), String> {
        self.desk.cancel(persona_id)
    }
    async fn set_model(&self, persona_id: &str, model_id: &str) -> Result<SessionInfo, String> {
        self.desk.set_model(persona_id, model_id).await
    }
    async fn set_mode(&self, persona_id: &str, mode_id: &str) -> Result<SessionInfo, String> {
        self.desk.set_mode(persona_id, mode_id).await
    }
    async fn set_config(
        &self,
        persona_id: &str,
        config_id: &str,
        value: &str,
    ) -> Result<SessionInfo, String> {
        self.desk.set_config(persona_id, config_id, value).await
    }
    fn models_efforts(&self, model_id: &str) -> crate::contract::EffortChoices {
        self.desk.models_efforts(model_id)
    }
    async fn answer_permission(
        &self,
        persona_id: &str,
        request_id: &str,
        option_id: &str,
    ) -> Result<(), String> {
        self.desk
            .answer_permission(persona_id, request_id, option_id)
            .await
    }
    fn answer_human(
        &self,
        persona_id: &str,
        action_id: &str,
        status: crate::contract::HumanAnswer,
        note: Option<String>,
    ) -> Result<(), String> {
        self.desk.answer_human(persona_id, action_id, status, note)
    }
    fn link_teammates(&self, a: &str, b: &str) -> Result<(), String> {
        self.desk.link_teammates(a, b)
    }
    fn unlink_teammates(&self, a: &str, b: &str) -> Result<(), String> {
        self.desk.unlink_teammates(a, b)
    }
    fn resume_link(&self, a: &str, b: &str) -> Result<(), String> {
        self.desk.resume_link(a, b)
    }
    async fn start_fresh_chapter(
        &self,
        persona_id: &str,
    ) -> Result<crate::contract::ChapterSummary, String> {
        self.desk.start_fresh_chapter(persona_id).await
    }
    async fn resume_chapter(
        &self,
        persona_id: &str,
    ) -> Result<crate::contract::ChapterSummary, String> {
        self.desk.resume_chapter(persona_id).await
    }
    fn info(&self, persona_id: &str) -> SessionInfo {
        self.desk.info(persona_id)
    }
    fn subscribe_info(&self) -> broadcast::Receiver<SessionInfo> {
        self.desk.subscribe_info()
    }
    fn subscribe_deltas(&self) -> broadcast::Receiver<StreamDelta> {
        self.desk.subscribe_deltas()
    }
    fn credential_create(
        &self,
        provider_id: &str,
        label: &str,
        secret: &str,
    ) -> Result<crate::contract::Credential, String> {
        self.desk.credential_create(provider_id, label, secret)
    }
    fn credential_revoke(&self, id: &str) -> Result<(), String> {
        self.desk.credential_revoke(id)
    }
    fn credential_delete(&self, id: &str) -> Result<(), String> {
        self.desk.credential_delete(id)
    }
    async fn credential_login(
        &self,
        provider_id: &str,
    ) -> Result<crate::contract::LoginPrompt, String> {
        self.desk.credential_login(provider_id).await
    }
    fn login_status(&self, login_id: &str) -> Result<crate::contract::LoginStatus, String> {
        self.desk.login_status(login_id)
    }
    fn credentials(&self) -> Vec<crate::contract::Credential> {
        self.desk.credentials()
    }
    async fn backends(&self) -> Vec<crate::contract::BackendChoice> {
        self.desk.backends().await
    }
    fn skills(&self, persona_id: Option<&str>) -> Result<Vec<crate::contract::SkillEntry>, String> {
        self.desk.skills(persona_id)
    }
    fn models(&self) -> Vec<crate::contract::ConfigChoice> {
        self.desk.models()
    }
    fn models_catalog(
        &self,
        provider_id: &str,
    ) -> Result<Vec<crate::contract::CatalogModel>, String> {
        self.desk.models_catalog(provider_id)
    }
    fn import(&self, from: &std::path::Path) -> Result<crate::import::Report, String> {
        self.desk.import(from)
    }
    fn teammate_tools(&self, persona_id: &str) -> Option<crate::contract::TeammateToolLedger> {
        self.desk.teammate_tools(persona_id)
    }
    fn schedule_create(
        &self,
        persona_id: &str,
        kind: crate::contract::ScheduleKind,
        when: Option<i64>,
        every: Option<i64>,
        prompt: &str,
        quiet: bool,
    ) -> Result<crate::contract::ScheduledJob, String> {
        self.desk
            .schedule_create(persona_id, kind, when, every, prompt, quiet)
    }
    fn schedule_list(&self) -> Vec<crate::contract::ScheduledJob> {
        self.desk.schedule_list()
    }
    fn schedule_cancel(&self, id: &str) -> Result<(), String> {
        self.desk.schedule_cancel(id)
    }
    fn schedule_set_quiet(&self, id: &str, quiet: bool) -> Result<(), String> {
        self.desk.schedule_set_quiet(id, quiet)
    }
    fn peer_threads(&self, persona_id: &str) -> Vec<crate::contract::PeerThreadSummary> {
        self.desk.peer_threads(persona_id)
    }
    fn mark_peer_read(&self, key: &str, event_ids: &[String]) -> usize {
        self.desk.mark_peer_read(key, event_ids)
    }
    async fn credential_refresh_models(
        &self,
        provider_id: &str,
    ) -> Result<Vec<crate::contract::CatalogModel>, String> {
        self.desk.credential_refresh_models(provider_id).await
    }
    fn forget(&self, persona_id: &str) {
        self.desk.forget(persona_id)
    }
    async fn computer_runtimes(&self) -> Vec<crate::contract::RuntimeReport> {
        self.desk.computer_runtimes().await
    }
    fn computer_releases(&self) -> crate::contract::ComputerReleases {
        self.desk.computer_releases()
    }
    async fn computer_releases_check(&self) -> crate::contract::ComputerReleases {
        self.desk.computer_releases_check().await
    }
    async fn computer_status(
        &self,
        _persona_id: &str,
    ) -> Result<crate::contract::ComputerStatus, String> {
        let viewer = self.viewer.lock().unwrap().clone();
        Ok(crate::contract::ComputerStatus {
            state: if viewer.is_some() {
                crate::contract::ComputerState::Running
            } else {
                crate::contract::ComputerState::Stopped
            },
            url: None,
            viewer,
            release: None,
            available: None,
            update_failed: None,
        })
    }
    async fn computer_stop(&self, persona_id: &str) -> Result<(), String> {
        self.desk.computer_stop(persona_id).await
    }
    async fn computer_remove(&self, persona_id: &str) -> Result<(), String> {
        self.desk.computer_remove(persona_id).await
    }
    async fn computer_update(&self, persona_id: &str) -> Result<(), String> {
        self.desk.computer_update(persona_id).await
    }
}

/// A computer's viewer socket with nothing behind it: one frame the moment a
/// viewer connects, then every text message handed straight back, and a note
/// of the query it was asked with.
#[allow(clippy::result_large_err)]
async fn fake_computer() -> (u16, Arc<std::sync::Mutex<Option<String>>>) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let asked = Arc::new(std::sync::Mutex::new(None));
    let seen = asked.clone();
    tokio::spawn(async move {
        let (stream, _) = listener.accept().await.unwrap();
        let noted = seen.clone();
        let mut socket = tokio_tungstenite::accept_hdr_async(
            stream,
            move |request: &tokio_tungstenite::tungstenite::handshake::server::Request,
                  response: tokio_tungstenite::tungstenite::handshake::server::Response| {
                *noted.lock().unwrap() = request.uri().query().map(str::to_owned);
                Ok(response)
            },
        )
        .await
        .unwrap();
        socket
            .send(Message::binary(b"\x89PNG frame".to_vec()))
            .await
            .unwrap();
        while let Some(Ok(message)) = socket.next().await {
            let Message::Text(text) = message else {
                continue;
            };
            if socket.send(Message::text(text.to_string())).await.is_err() {
                break;
            }
        }
    });
    (port, asked)
}

#[tokio::test]
async fn a_phone_reaches_a_running_computer_through_the_desk_and_never_holds_its_bearer() {
    let (port, asked) = fake_computer().await;
    let (h, room) = Harness::with_computer().await;
    *room.viewer.lock().unwrap() = Some(format!("http://127.0.0.1:{port}/#secret-bearer"));
    let grant = h.pair().await;
    let token = grant["token"].as_str().unwrap();
    let mut screen = h.socket_at("/computer/ada/ws", token).await.unwrap();
    // The frame the computer sends on connect arrives as it is.
    let first = tokio::time::timeout(Duration::from_secs(3), screen.next())
        .await
        .unwrap()
        .unwrap()
        .unwrap();
    assert!(first.is_binary());
    assert_eq!(first.into_data().as_ref(), b"\x89PNG frame");
    // What the phone says reaches the computer as it was said.
    screen
        .send(Message::text(r#"{"t":"control","take":true}"#))
        .await
        .unwrap();
    let echoed = tokio::time::timeout(Duration::from_secs(3), screen.next())
        .await
        .unwrap()
        .unwrap()
        .unwrap();
    assert_eq!(echoed.to_text().unwrap(), r#"{"t":"control","take":true}"#);
    // The computer was asked with the desk's bearer, which the phone never had.
    assert_eq!(
        asked.lock().unwrap().as_deref(),
        Some("token=secret-bearer")
    );
    assert!(!grant.to_string().contains("secret-bearer"));
}

#[tokio::test]
async fn the_computer_door_is_shut_to_the_unpaired_the_unnamed_and_the_stopped() {
    use tokio_tungstenite::tungstenite::Error;
    let (h, room) = Harness::with_computer().await;
    let grant = h.pair().await;
    let token = grant["token"].as_str().unwrap();
    let status_of = |error: Error| match error {
        Error::Http(response) => response.status().as_u16(),
        other => panic!("expected an HTTP refusal, got {other:?}"),
    };
    // No grant: nothing is said about whether the teammate exists.
    let refused = h.socket_at("/computer/ada/ws", &"0".repeat(64)).await;
    assert_eq!(status_of(refused.err().unwrap()), 401);
    // A path that names anything but a teammate id is not a door.
    let refused = h.socket_at("/computer/../ws", token).await;
    assert_eq!(status_of(refused.err().unwrap()), 404);
    let refused = h.socket_at("/computer/ada/ws/extra", token).await;
    assert_eq!(status_of(refused.err().unwrap()), 404);
    // A computer that is not running has no socket to reach.
    *room.viewer.lock().unwrap() = None;
    let refused = h.socket_at("/computer/ada/ws", token).await;
    assert_eq!(status_of(refused.err().unwrap()), 409);
}

#[tokio::test]
async fn revoking_the_phone_drops_its_computer_socket() {
    let (port, _asked) = fake_computer().await;
    let (h, room) = Harness::with_computer().await;
    *room.viewer.lock().unwrap() = Some(format!("http://127.0.0.1:{port}/#secret-bearer"));
    let grant = h.pair().await;
    let mut screen = h
        .socket_at("/computer/ada/ws", grant["token"].as_str().unwrap())
        .await
        .unwrap();
    let _frame = tokio::time::timeout(Duration::from_secs(3), screen.next())
        .await
        .unwrap()
        .unwrap()
        .unwrap();
    h.remote
        .revoke(grant["deviceId"].as_str().unwrap())
        .unwrap();
    let ended = tokio::time::timeout(Duration::from_secs(3), async {
        loop {
            match screen.next().await {
                None | Some(Err(_)) | Some(Ok(Message::Close(_))) => break,
                Some(Ok(_)) => {}
            }
        }
    })
    .await;
    assert!(ended.is_ok(), "the socket stayed open after revocation");
}

#[test]
fn the_computer_target_is_read_off_the_desk_s_own_viewer_and_only_while_running() {
    use crate::contract::{ComputerState, ComputerStatus};
    let status = |state: ComputerState, viewer: Option<&str>| ComputerStatus {
        state,
        url: None,
        viewer: viewer.map(str::to_owned),
        release: None,
        available: None,
        update_failed: None,
    };
    assert_eq!(
        server::computer_target(&status(
            ComputerState::Running,
            Some("http://127.0.0.1:41234/#abc")
        )),
        Some((41234, "abc".to_string()))
    );
    assert_eq!(
        server::computer_target(&status(
            ComputerState::Stopped,
            Some("http://127.0.0.1:41234/#abc")
        )),
        None
    );
    assert_eq!(
        server::computer_target(&status(ComputerState::Running, None)),
        None
    );
    assert_eq!(
        server::computer_target(&status(
            ComputerState::Running,
            Some("http://127.0.0.1:41234/#")
        )),
        None
    );
    assert_eq!(
        server::computer_target(&status(
            ComputerState::Running,
            Some("http://example.com:41234/#abc")
        )),
        None
    );
}
