//! These tests enter the real desk through HTTPS/WSS; the trust root is the
//! certificate generated by this disposable listener, never an insecure client.
use super::*;
use crate::{credentials::tests::MemoryStore, desk::Desk, wire::Door};
use futures_util::{SinkExt, StreamExt};
use std::time::Duration;
use tokio::net::TcpStream;
use tokio_rustls::{TlsConnector, client::TlsStream, rustls};
use tokio_tungstenite::{
    WebSocketStream,
    tungstenite::{Message, client::IntoClientRequest},
};

type Socket = WebSocketStream<TlsStream<TcpStream>>;
struct Harness {
    root: tempfile::TempDir,
    remote: Arc<Remote>,
    desk: Arc<Desk>,
    store: Arc<MemoryStore>,
    http: reqwest::Client,
    tls: TlsConnector,
}
impl Harness {
    async fn new() -> Self {
        let root = tempfile::tempdir().unwrap();
        // Harnesses run side by side; none may claim the install default port
        // another one's re-enable expects to get back.
        let port = std::net::TcpListener::bind("[::]:0")
            .or_else(|_| std::net::TcpListener::bind("0.0.0.0:0"))
            .unwrap()
            .local_addr()
            .unwrap()
            .port();
        fs::write(
            root.path().join("remote.json"),
            json!({"desktopId": Uuid::new_v4(), "host": network::ALL, "port": port, "enabled": false, "grants": []}).to_string(),
        )
        .unwrap();
        let store = Arc::new(MemoryStore::default());
        let desk = Arc::new(Desk::open_with_store(root.path(), store.clone()).unwrap());
        let remote =
            Remote::open_with_store(root.path(), desk.log.clone(), desk.clone(), store.clone())
                .unwrap();
        assert!(!remote.status().enabled);
        remote.configure(true, network::ALL).await.unwrap();
        let identity: Identity =
            serde_json::from_slice(&remote.identity.read().unwrap().unwrap()).unwrap();
        let mut roots = rustls::RootCertStore::empty();
        roots
            .add(rustls::pki_types::CertificateDer::from(
                identity.certificate.clone(),
            ))
            .unwrap();
        let config = rustls::ClientConfig::builder_with_provider(Arc::new(
            rustls::crypto::aws_lc_rs::default_provider(),
        ))
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(roots)
        .with_no_client_auth();
        let http = reqwest::Client::builder()
            .no_proxy()
            .add_root_certificate(reqwest::Certificate::from_der(&identity.certificate).unwrap())
            .build()
            .unwrap();
        Self {
            root,
            remote,
            desk,
            store,
            http,
            tls: TlsConnector::from(Arc::new(config)),
        }
    }
    fn endpoint(&self) -> String {
        self.remote.status().endpoint.unwrap()
    }
    async fn claim(&self, value: &Value) -> reqwest::Response {
        self.http
            .post(format!("{}/pair", self.endpoint()))
            .json(value)
            .send()
            .await
            .unwrap()
    }
    async fn post(&self, path: &str, value: &Value) -> reqwest::Response {
        self.http
            .post(format!("{}{path}", self.endpoint()))
            .json(value)
            .send()
            .await
            .unwrap()
    }
    async fn pair(&self) -> Value {
        let invite = self.remote.pairing().unwrap().invitation;
        self.claim_invitation(invite).await
    }
    /// Scans the invitation already on screen rather than minting one.
    async fn pair_current(&self) -> Value {
        let invite = self
            .remote
            .state
            .lock()
            .unwrap()
            .invitation
            .as_ref()
            .unwrap()
            .value
            .clone();
        self.claim_invitation(invite).await
    }
    async fn claim_invitation(&self, invite: PairingInvitation) -> Value {
        self.claim(&json!({"invitationId":invite.invitation_id,"secret":invite.secret,"claimId":Uuid::new_v4(),"name":"Test phone"}))
            .await.error_for_status().unwrap().json().await.unwrap()
    }
    async fn socket(&self, token: &str) -> Result<Socket, tokio_tungstenite::tungstenite::Error> {
        let endpoint = self.endpoint();
        let stream = TcpStream::connect(endpoint.trim_start_matches("https://"))
            .await
            .unwrap();
        let tls = self
            .tls
            .connect(
                rustls::pki_types::ServerName::try_from(
                    url::Url::parse(&endpoint)
                        .unwrap()
                        .host_str()
                        .unwrap()
                        .trim_matches(['[', ']'])
                        .to_owned(),
                )
                .unwrap(),
                stream,
            )
            .await
            .unwrap();
        let mut request = format!("{}/ws", endpoint.replace("https:", "wss:"))
            .into_client_request()
            .unwrap();
        request
            .headers_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        tokio_tungstenite::client_async(request, tls)
            .await
            .map(|v| v.0)
    }
}
async fn read(socket: &mut Socket) -> Value {
    let frame = tokio::time::timeout(Duration::from_secs(3), socket.next())
        .await
        .unwrap()
        .unwrap()
        .unwrap();
    serde_json::from_str(frame.to_text().unwrap()).unwrap()
}
async fn send(socket: &mut Socket, frame: Value) {
    socket.send(Message::text(frame.to_string())).await.unwrap();
}

#[tokio::test]
async fn pairing_is_single_use_persistent_and_revocation_closes_the_live_wire() {
    let h = Harness::new().await;
    let invitation = h.remote.pairing().unwrap().invitation;
    let mut claim = json!({"invitationId":invitation.invitation_id,"secret":"wrong","claimId":Uuid::new_v4(),"name":"My phone"});
    assert_eq!(h.claim(&claim).await.status(), 403);
    claim["secret"] = json!(invitation.secret);
    let grant: Value = h.claim(&claim).await.json().await.unwrap();
    assert_eq!(grant, h.claim(&claim).await.json::<Value>().await.unwrap());
    claim["claimId"] = json!(Uuid::new_v4());
    assert_eq!(h.claim(&claim).await.status(), 403);
    assert!(h.socket("desk-token").await.is_err());
    let token = grant["token"].as_str().unwrap();
    assert!(
        !fs::read_to_string(h.root.path().join("remote.json"))
            .unwrap()
            .contains(token)
    );
    let mut socket = h.socket(token).await.unwrap();
    assert_eq!(read(&mut socket).await["mode"], "team");
    h.remote
        .revoke(grant["deviceId"].as_str().unwrap())
        .unwrap();
    let closed = tokio::time::timeout(Duration::from_secs(3), socket.next())
        .await
        .unwrap();
    assert!(!matches!(closed, Some(Ok(Message::Text(_)))));
    assert!(h.socket(token).await.is_err());
    assert_eq!(h.claim(&claim).await.status(), 403);
    let next = h.pair().await;
    let endpoint = h.endpoint();
    let fingerprint = h.remote.pairing().unwrap().invitation.certificate_sha256;
    h.remote.configure(false, network::ALL).await.unwrap();
    assert!(
        TcpStream::connect(endpoint.trim_start_matches("https://"))
            .await
            .is_err()
    );
    let restored = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        h.store.clone(),
    )
    .unwrap();
    restored.configure(true, network::ALL).await.unwrap();
    assert_eq!(restored.status().endpoint.unwrap(), endpoint);
    assert_eq!(
        restored.pairing().unwrap().invitation.certificate_sha256,
        fingerprint
    );
    assert!(
        restored
            .authenticate(next["token"].as_str().unwrap())
            .is_some()
    );
    restored.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn a_phone_sees_the_real_roster_and_tape_but_cannot_administer_the_desk() {
    let h = Harness::new().await;
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}/v1", listener.local_addr().unwrap());
    let calls = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let counted = calls.clone();
    let requests = Arc::new(Mutex::new(Vec::<Value>::new()));
    let captured = requests.clone();
    let app = axum::Router::new().route("/v1/chat/completions", axum::routing::post(move |body: String| {
        captured.lock().unwrap().push(serde_json::from_str(&body).unwrap());
        counted.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        async {
            let chunk = json!({"id":"chat_1","object":"chat.completion.chunk","created":1,"model":"test","choices":[{"index":0,"delta":{"role":"assistant","content":"A real core turn"},"finish_reason":null}]});
            let end = json!({"id":"chat_1","object":"chat.completion.chunk","created":1,"model":"test","choices":[{"index":0,"delta":{},"finish_reason":"stop"}]});
            ([("Content-Type", "text/event-stream")], format!("data: {chunk}\n\ndata: {end}\n\ndata: [DONE]\n\n"))
        }
    }));
    let model = tokio::spawn(async move {
        axum::serve(listener, app).await.unwrap();
    });
    h.desk.credential_custom_save(None, serde_json::from_value(json!({"name":"Fixture", "baseUrl":base, "api":"chat_completions", "secret":"", "models":["test"]})).unwrap()).unwrap();
    let door = Door::bind(h.desk.log.clone(), "test-desk".into(), h.desk.clone()).unwrap();
    let port = door.port();
    let task = tokio::spawn(door.run());
    let (mut desk, _) =
        tokio_tungstenite::connect_async(format!("ws://127.0.0.1:{port}/ws?token=test-desk"))
            .await
            .unwrap();
    desk.send(Message::text(json!({"id":1,"cmd":"persona.create","params":{"draft":{"name":"Ada","goal":"Help with the project","cwd":h.root.path().to_str().unwrap()}}}).to_string())).await.unwrap();
    let created: Value =
        serde_json::from_str(desk.next().await.unwrap().unwrap().to_text().unwrap()).unwrap();
    let persona = created["result"]["id"].as_str().unwrap();
    let grant = h.pair().await;
    let mut phone = h.socket(grant["token"].as_str().unwrap()).await.unwrap();
    read(&mut phone).await;
    for frame in [
        json!({"id":1,"cmd":"credential.list"}),
        json!({"id":1,"cmd":"settings.update","params":{"patch":{}}}),
        json!({"id":1,"sub":"room"}),
        json!({"id":1,"cmd":"session.prompt","params":{"personaId":persona,"text":"bad","attachments":[]}}),
    ] {
        send(&mut phone, frame).await;
        assert_eq!(read(&mut phone).await["ok"], false);
    }
    send(&mut phone, json!({"id":2,"sub":{"view":"roster"}})).await;
    assert_eq!(read(&mut phone).await["ok"], true);
    assert_eq!(
        read(&mut phone).await["snapshot"][0]["persona"]["name"],
        "Ada"
    );
    send(&mut phone, json!({"id":3,"sub":{"tape":persona}})).await;
    assert_eq!(read(&mut phone).await["ok"], true);
    assert_eq!(read(&mut phone).await["snapshot"], json!([]));
    // The core remains the writer; this tests that its append reaches the TLS subscription.
    h.desk
        .log
        .append(
            &crate::log::StreamId::Tape(persona.into()),
            &json!({"id":"one","kind":"agent","ts":1,"text":"From the real tape"}),
        )
        .unwrap();
    loop {
        let frame = read(&mut phone).await;
        if frame["sub"] == 3 {
            assert_eq!(frame["event"]["text"], "From the real tape");
            break;
        }
    }
    // The phone is the first client to start this teammate. Retransmitting
    // its operation after acceptance must not start a second model turn.
    let attachment = Uuid::new_v4();
    send(&mut phone, json!({"id":30,"cmd":"mobile.attachment","params":{"upload":{"id":attachment,"name":"brief.txt","mimeType":"text/plain","size":5,"offset":0,"data":"aGVsbG8="}}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 30 {
            assert_eq!(frame["result"]["complete"], true, "{frame}");
            break;
        }
    }
    let operation = Uuid::new_v4();
    send(&mut phone, json!({"id":4,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"","attachmentIds":[attachment]}})).await;
    let mut accepted = false;
    let mut answered = false;
    while !accepted || !answered {
        let frame = read(&mut phone).await;
        if frame["id"] == 4 {
            assert_eq!(frame["result"]["state"], "accepted", "{frame}");
            accepted = true;
        }
        if frame["sub"] == 3
            && frame["event"]["kind"] == "agent"
            && frame["event"]["text"] == "A real core turn"
        {
            answered = true;
        }
    }
    send(&mut phone, json!({"id":5,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"","attachmentIds":[attachment]}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 5 {
            assert_eq!(frame["result"]["state"], "accepted");
            break;
        }
    }
    assert_eq!(calls.load(std::sync::atomic::Ordering::SeqCst), 1);
    let tape = h.desk.log.load(&crate::log::StreamId::Tape(persona.into()));
    let users: Vec<_> = tape
        .iter()
        .filter(|event| event["kind"] == "user")
        .collect();
    assert_eq!(users.len(), 1);
    assert_eq!(users[0]["text"], "");
    assert_eq!(users[0]["attachments"][0]["name"], "brief.txt");
    let path = users[0]["attachments"][0]["path"].as_str().unwrap();
    assert_eq!(fs::read(path).unwrap(), b"hello");
    assert!(requests.lock().unwrap()[0].to_string().contains(path));
    send(&mut phone, json!({"id":6,"cmd":"mobile.prompt","params":{"operationId":operation,"personaId":persona,"text":"changed","attachmentIds":[]}})).await;
    loop {
        let frame = read(&mut phone).await;
        if frame["id"] == 6 {
            assert_eq!(frame["ok"], false);
            break;
        }
    }
    h.remote.configure(false, network::ALL).await.unwrap();
    model.abort();
    task.abort();
}

#[tokio::test]
async fn an_uncertain_prompt_is_never_replayed_and_operation_ids_cannot_change_meaning() {
    let h = Harness::new().await;
    let grant = h.pair().await;
    let phone = h
        .remote
        .authenticate(grant["token"].as_str().unwrap())
        .unwrap();
    let operation = Uuid::new_v4().to_string();
    let dir = h.root.path().join("remote-receipts").join(&phone.id);
    fs::create_dir_all(&dir).unwrap();
    let path = dir.join(format!("{operation}.json"));
    let receipt = Receipt {
        digest: hash(&json!(["persona", "hello"]).to_string()),
        result: None,
    };
    atomic_write(&path, &serde_json::to_vec(&receipt).unwrap()).unwrap();
    assert_eq!(
        phone
            .prompt(&operation, "persona", "hello", &[])
            .await
            .unwrap()["state"],
        "unknown"
    );
    assert!(
        phone
            .prompt(&operation, "persona", "changed", &[])
            .await
            .is_err()
    );
    let receipt = Receipt {
        result: Some(Ok(())),
        ..receipt
    };
    atomic_write(&path, &serde_json::to_vec(&receipt).unwrap()).unwrap();
    assert_eq!(
        phone
            .prompt(&operation, "persona", "hello", &[])
            .await
            .unwrap()["state"],
        "accepted"
    );
    h.remote.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn all_interfaces_are_the_default_and_every_advertised_ip_has_valid_tls() {
    let h = Harness::new().await;
    let status = h.remote.status();
    assert_eq!(status.host, network::ALL);
    assert!(status.enabled);
    assert_eq!(status.endpoints.len(), status.addresses.len());
    for endpoint in &status.endpoints {
        let response = h
            .http
            .get(format!("{endpoint}/missing"))
            .timeout(Duration::from_secs(3))
            .send()
            .await
            .unwrap();
        assert_eq!(response.status(), 404);
    }
    let invitation = h.remote.pairing().unwrap().invitation;
    assert_eq!(Some(invitation.endpoint), status.endpoint);
    for host in ["127.0.0.1", "127.2.3.4", "::1", "0.0.0.0", "::"] {
        assert!(h.remote.configure(true, host).await.is_err());
        assert_eq!(h.remote.status().endpoints, status.endpoints);
    }
    let grant = h.pair().await;
    let token = grant["token"].as_str().unwrap();
    let specific = status.addresses[0].clone();
    let narrowed = h.remote.configure(true, &specific).await.unwrap();
    assert_eq!(narrowed.host, specific);
    assert_eq!(narrowed.endpoints, vec![status.endpoint.clone().unwrap()]);
    assert!(h.remote.authenticate(token).is_some());
    assert_eq!(
        h.remote.pairing().unwrap().invitation.certificate_sha256,
        invitation.certificate_sha256
    );
    for other in status.endpoints.iter().skip(1) {
        let result = h
            .http
            .get(format!("{other}/missing"))
            .timeout(Duration::from_secs(1))
            .send()
            .await;
        assert!(result.is_err(), "restricted listener accepted {other}");
    }
    let off = h.remote.configure(false, network::ALL).await.unwrap();
    assert!(!off.enabled);
    assert_eq!(off.host, network::ALL);
    assert!(off.endpoints.is_empty());
    assert!(h.remote.authenticate(token).is_none());
    assert_eq!(
        h.remote
            .configure(true, network::ALL)
            .await
            .unwrap()
            .endpoints,
        status.endpoints
    );
    assert!(h.remote.authenticate(token).is_some());
    h.remote.configure(false, network::ALL).await.unwrap();
}

#[tokio::test]
async fn a_saved_loopback_selection_migrates_to_all_host_ips() {
    let h = Harness::new().await;
    h.remote.configure(false, network::ALL).await.unwrap();
    let path = h.root.path().join("remote.json");
    let mut saved: Saved = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    saved.host = "127.0.0.1".into();
    atomic_write(&path, &serde_json::to_vec(&saved).unwrap()).unwrap();
    let restored = Remote::open_with_store(
        h.root.path(),
        h.desk.log.clone(),
        h.desk.clone(),
        h.store.clone(),
    )
    .unwrap();
    assert_eq!(restored.status().host, network::ALL);
    assert!(!restored.status().enabled);
    assert!(
        restored
            .status()
            .addresses
            .iter()
            .all(|host| network::reachable(host.parse().unwrap()))
    );
    restored.configure(true, network::ALL).await.unwrap();
    let saved: Saved = serde_json::from_slice(&fs::read(path).unwrap()).unwrap();
    assert_eq!(saved.host, network::ALL);
    restored.configure(false, network::ALL).await.unwrap();
}

/// The phone's half of the manual exchange, as the mobile client does it.
struct TypingPhone {
    claim_id: String,
    secret: Scalar,
    public: String,
}
impl TypingPhone {
    fn new(code: &str) -> Self {
        let claim_id = Uuid::new_v4().to_string();
        let secret = pake::random_scalar();
        let public = pake::public(code, &claim_id, &secret);
        Self {
            claim_id,
            secret,
            public,
        }
    }
    async fn start(&self, h: &Harness) -> reqwest::Response {
        h.post(
            "/pair/manual/start",
            &json!({"claimId": self.claim_id, "name": "Typed phone", "phonePublic": self.public}),
        )
        .await
    }
    /// `cert` is what the phone believes it connected to.
    fn confirm(&self, started: &Value, cert: &str) -> pake::Confirmations {
        let desktop_public = started["desktopPublic"].as_str().unwrap();
        pake::confirmations(
            started["desktopId"].as_str().unwrap(),
            &self.claim_id,
            &self.secret,
            &pake::decode_public(desktop_public).unwrap(),
            &self.public,
            desktop_public,
            cert,
        )
        .unwrap()
    }
    async fn finish(&self, h: &Harness, confirm: &str) -> reqwest::Response {
        h.post(
            "/pair/manual/finish",
            &json!({"claimId": self.claim_id, "confirm": confirm}),
        )
        .await
    }
}

#[tokio::test]
async fn a_typed_code_pairs_through_a_pake_bound_to_the_certificate() {
    let h = Harness::new().await;
    let pairing = h.remote.pairing().unwrap();
    let manual = pairing.manual;
    let cert = pairing.invitation.certificate_sha256.clone();
    assert!(manual.code.len() == 6 && manual.code.bytes().all(|b| b.is_ascii_digit()));
    assert_eq!(
        network::endpoint(&manual.address, manual.port),
        pairing.invitation.endpoint
    );
    assert_eq!(manual.expires_at, pairing.invitation.expires_at);

    // A guess with the wrong code, and the right code seen through a relay's
    // certificate, both fail the same way and each burns its session.
    let guessing = TypingPhone::new("000000");
    let started: Value = guessing.start(&h).await.json().await.unwrap();
    assert_eq!(started["desktopId"], pairing.invitation.desktop_id);
    assert_eq!(started["expiresAt"], manual.expires_at);
    let wrong = guessing.confirm(&started, &cert).phone;
    let refused = guessing.finish(&h, &wrong).await;
    assert_eq!(refused.status(), 403);
    assert_eq!(refused.json::<Value>().await.unwrap()["error"], "bad_code");
    assert_eq!(guessing.finish(&h, &wrong).await.status(), 403);

    let relayed = TypingPhone::new(&manual.code);
    let started: Value = relayed.start(&h).await.json().await.unwrap();
    let seen_through_relay = relayed.confirm(&started, &hex::encode([7u8; 32])).phone;
    let refused = relayed.finish(&h, &seen_through_relay).await;
    assert_eq!(refused.json::<Value>().await.unwrap()["error"], "bad_code");

    // The real phone: the desktop's confirmation proves it saw the same
    // certificate, and the token it hands over opens the wire.
    let phone = TypingPhone::new(&manual.code);
    let started: Value = phone.start(&h).await.json().await.unwrap();
    let tags = phone.confirm(&started, &cert);
    let granted: Value = phone.finish(&h, &tags.phone).await.json().await.unwrap();
    assert_eq!(granted["confirm"], tags.desktop);
    assert_eq!(granted["certificateSha256"], cert);
    assert_eq!(granted["desktopId"], pairing.invitation.desktop_id);
    assert_eq!(
        granted,
        phone
            .finish(&h, &tags.phone)
            .await
            .json::<Value>()
            .await
            .unwrap()
    );
    let mut socket = h.socket(granted["token"].as_str().unwrap()).await.unwrap();
    assert_eq!(read(&mut socket).await["mode"], "team");
    assert_eq!(h.remote.status().devices[0].name, "Typed phone");
    // The pairing session is spent on both paths.
    let invite = pairing.invitation;
    let scan = h.claim(&json!({"invitationId": invite.invitation_id, "secret": invite.secret, "claimId": Uuid::new_v4(), "name": "Scanner"})).await;
    assert_eq!(scan.status(), 403);
    assert_eq!(TypingPhone::new(&manual.code).start(&h).await.status(), 403);

    // Five wrong confirmations kill the code, and a scan closes the typed path.
    let manual = h.remote.pairing().unwrap().manual;
    for attempt in 1..=5 {
        let guess = TypingPhone::new("111111");
        let started: Value = guess.start(&h).await.json().await.unwrap();
        let refused = guess
            .finish(&h, &guess.confirm(&started, &cert).phone)
            .await;
        let expected = if attempt == 5 {
            (429, "too_many_attempts")
        } else {
            (403, "bad_code")
        };
        assert_eq!(refused.status(), expected.0, "attempt {attempt}");
        assert_eq!(refused.json::<Value>().await.unwrap()["error"], expected.1);
    }
    let dead = TypingPhone::new(&manual.code).start(&h).await;
    assert_eq!(dead.status(), 403);
    assert_eq!(
        dead.json::<Value>().await.unwrap()["error"],
        "pairing_closed"
    );
    h.remote.state.lock().unwrap().attempts = 0;
    let manual = h.remote.pairing().unwrap().manual;
    h.pair_current().await;
    assert_eq!(TypingPhone::new(&manual.code).start(&h).await.status(), 403);
    let junk = h
        .post(
            "/pair/manual/start",
            &json!({"claimId": Uuid::new_v4(), "name": "x", "phonePublic": hex::encode([0u8; 32])}),
        )
        .await;
    assert_eq!(junk.status(), 400);
    h.remote.configure(false, network::ALL).await.unwrap();
}
